### ISSUE TITLE
peer-info and cipher negotiation

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#102]
From browsing the openvpn source code and documentation I discovered the "peer-info" mechanism. It is used to push information about the client such as version, platform, supported data channel ciphers: `IV_VER`, `IV_PLAT`, `IV_CIPHERS`. The capability to negotiate data channel ciphers is communicated by pushing `IV_NCP=2`, and there is a quirk with how openvpn 2.4 handles that (TODO: describe the quirk), but otherwise I believe it is the first value in the server's `IV_CIPHERS` the client also announced.

The peer-info is pushed in tls-data, and the code has a comment that additional data is pushed - this is the peer-info. It seems an openvpn server will push the empty wire string if the client didn't send any peer-info.
https://github.com/robur-coop/miragevpn/blob/64f2b7dd40613d935487c526d3089244ddd4816b/src/packet.ml#L375-L381

**Comment by hannesm** [comment]
Thanks for your investigation. Seems like this protocol is growing in complexity... :/ I also noticed there's --data-cipher now... I'm not sure how much of that stuff we actually want to support (and would focus on the other things, such as tls-crypt-v2, first) :)

**Comment by hannesm** [comment]
fixed by #121
