### ISSUE TITLE
[NCP] "Modern" protocol key exchange (IV_PROTO bit 3)

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#103]
The draft openvpn-rfc specification describes the key exchange message and how there's one for legacy clients (what we implement, I think), and one for "modern" protocol implementations that use RFC5705 export keying material. Support for this mechanism is communicated using bit 3 in `IV_PROTO` in the peer-info:
https://github.com/OpenVPN/openvpn-rfc/blob/bbde60d7f28a5436e21b3f475788f7922e0d9339/openvpn-wire-protocol.xml#L1417-L1418

From the openvpn Changes.rst it seems it was introduced in openvpn 2.4, and is preferred since openvpn 2.6.

**Comment by reynir** [comment]
Further details from `doc_key_generation.h`:

    When the client sends the IV_PROTO_TLS_KEY_EXPORT flag and the server replies
    with `key-derivation tls-ekm` the RFC5705 key material exporter with the
    label EXPORTER-OpenVPN-datakeys is used for the key data.

**Comment by hannesm** [comment]
this requires changes to ocaml-tls (to expose the exporter secret). unclear whether it is worth doing?

**Comment by reynir** [comment]
I think it would be worth to implement _if_ the change was made to ocaml-tls. I am not sure it is worth working on adding more functionality to ocaml-tls if this is the only motivation. Maybe it is worth opening an issue on ocaml-tls to gather interest or keep this open? Or we can close this as wontfix.

**Comment by Neustradamus** [comment]
An important ticket ^^
