### ISSUE TITLE
Omit the timestamp when we compute the hmac

### ISSUE THREAD

**Issue by dinosaure** [robur-coop/miragevpn#104]
We probably should update the `Packet.to_be_signed_header`. /cc @reynir 

See:
https://github.com/robur-coop/miragevpn/blob/64f2b7dd40613d935487c526d3089244ddd4816b/src/packet.ml#L132-L156

**Comment by reynir** [comment]
To add the motivation for this is the openvpn-rfc document says the replay_packet_id (packet id + optional timestamp) is without the timestamp for tls-crypt-v2. This does not seem to correspond with what the openvpn source code does. As the openvpn-rfc seems to be wrong I am closing this.

Please reopen if this becomes relevant again.
