### ISSUE TITLE
my_hmac, their_hmac in type session only used in tls-auth

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#131]
When working on tls-crypt-v2 I was reviewing the existing code in order to figure out where to put the control channel encryption keys. It turns out the fields `my_hmac` and `their_hmac` of type session are set both in tls-auth clients and static clients, but they are only ever used in tls-auth clients.
https://github.com/robur-coop/miragevpn/blob/9a5714943ebf98f3d49a83090900a42171c547d9/src/state.ml#L204-L214

**Comment by hannesm** [comment]
thanks for your issue and the fix in #132
