### ISSUE TITLE
Refactor from Result.Infix to Result.Syntax

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#138]
In bb47bcd64a3fb8ca585b69d1260140b11727a815 the `Result` module got a submodule `Syntax` using the let-syntax for bind and map. It is in my opinion nicer to read the let-syntax than the infix syntax. It would be nice to rewrite all usage of the infix syntax to use the let-syntax.

**Comment by hannesm** [comment]
done in #143
