### ISSUE TITLE
Partial UDP packets are appended to the next packet

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#140]
I think this line should depend on the protocol. For TCP it is fine, but for UDP I think it is very wrong(?)
https://github.com/robur-coop/miragevpn/blob/17fc4134c1f609d21f3f0346eb30b33f53c1c8ab/src/engine.ml#L1320

**Comment by hannesm** [comment]
fixed by #139 (where `` `Tcp_partial `` got introduced)

**Comment by reynir** [comment]
Ah, true! I looked at this and didn't close it. This is a bit subtle. In engine.ml we don't check if protocol is <code>`Tcp</code>, but <code>`Tcp_partial</code> can only ever be returned if ``proto = `Tcp``. I will add a comment in the code!
