### ISSUE TITLE
IV_NCP=2 and OpenVPN 2.4

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#152]
We always send `IV_NCP=2`:
https://github.com/robur-coop/miragevpn/blob/35a8d96783695674913ee42379f8384b34d83fe9/src/engine.ml#L360
But in the cipher-negotiation section of the man page it says OpenVPN 2.5+ only send `IV_NCP=2` if `--data-ciphers` include AES-{128,256}-GCM.
https://github.com/OpenVPN/openvpn/blob/5af57e348ed3a5f451aca1bba5ba57b3a34e5d11/doc/man-sections/cipher-negotiation.rst?plain=1#L75-L76

Since OpenVPN 2.4 reached EOL in March this year maybe we can just drop `IV_NCP=2`? https://community.openvpn.net/openvpn/wiki/SupportedVersions

**Comment by hannesm** [comment]
as I understand it, openvpn 2.4 didn't had `IV_CIPHERS` at all, but the presence of IV_NCP was used to (implicitly) indicate that AES-GCM is supported...

still, we need to decide what the lower bound of openvpn is that we support... does https://repology.org/project/openvpn/versions help us to find an opinion?

**Comment by reynir** [comment]
Implemented in #154
