### ISSUE TITLE
Make Miragevpn.handle return `action list` over `action option`

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#180]
https://github.com/robur-coop/miragevpn/blob/522888fb3f8279bf617ddc09a53c2c31aedd8fa4/src/miragevpn.mli#L318-L322
And change the constructor `` `Payload of Cstruct.t ``. The reasoning being the code does a clumsy merge of payloads and things are dropped if merging a payload into a non-payload
https://github.com/robur-coop/miragevpn/blob/522888fb3f8279bf617ddc09a53c2c31aedd8fa4/src/miragevpn.mli#L279-L285

**Comment by hannesm** [comment]
done in a97a924
