### ISSUE TITLE
IV_PROTO tls-ekm does not work nicely with a debian server

### ISSUE THREAD

**Issue by hannesm** [robur-coop/miragevpn#181]
As remarked by @reynir in https://github.com/robur-coop/miragevpn/pull/169#issuecomment-1838147741:
I observed AEAD decrypt failures on both the OpenVPN™ server and the client when using tls 1.3 on my own debian server with both tls-crypt and tls-crypt-v2. Using tls 1.2 works fine however. I tested with the main branch and I can reproduce the same behavior (except for tls-crypt of course).

Interestingly I can't reproduce against the OpenVPN™ server running on FreeBSD.

@reynir: could you add OpenVPN version numbers to this issue so at a later point in time we can try to reproduce with the exact versions?

On the FreeBSD server, we use openvpn-2.6.8

**Comment by reynir** [comment]
I used openvpn 2.6.3 and a custom build with extra debug logging and tls-crypt protocol_dump fix 2.7_git. In both cases OpenSSL 1.1.1w is used.

**Comment by hannesm** [comment]
ah, good that you mention it -- we are using OpenSSL 1.1.1h-freebsd  22 Sep 2020 on the FreeBSD machine

**Comment by hannesm** [comment]
With https://github.com/mirleft/ocaml-tls/pull/495 I can establish an EKM session with TLS 1.3 between our server and client (both notun).

The old Debian server side issue may be related to https://github.com/openssl/openssl/issues/3940 -- but I wasn;t able to track down which OpenSSL versions are affected.

I'd suggest: let's get a tls release out, and then enable EKM in MirageVPN (and if we encounter another issue, we can revert).
