### ISSUE TITLE
Server: handle peerinfo

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#227]
Currently we don't do anything with the peerinfo sent from the client. The client may send `IV_PROTO` with bit 2 set which means the server **MAY** send a push reply. In practice it *seems* our client and the OpenVPN™ client sets `IV_PROTO` bit 2 and then never sends `PUSH REQUEST`. This results in the connection timing out because neither parties send any more packets.

(this analysis may not be right, but we should implement handling peerinfo in the server in any case)

**Comment by hannesm** [comment]
done in #229 :)
