### ISSUE TITLE
config parser does not like server config

### ISSUE THREAD

**Issue by whohoho** [robur-coop/miragevpn#23]
openvpn_config_parser.exe server.cfg 
openvpn_config_parser.exe: [INFO] Reading file "server.cfg"
openvpn_config_parser.exe: [WARNING] IGNORING "explicit-exit-notify" "1"
openvpn_config_parser.exe: [WARNING] IGNORING "ifconfig-pool-persist" "ipp.txt"
openvpn_config_parser.exe: [WARNING] IGNORING "status" "openvpn-status.log"
openvpn_config_parser.exe: [INFO] Reading file "ca.public.certificate"
openvpn_config_parser.exe: [DEBUG] x509 cert: CA
openvpn_config_parser.exe: [INFO] Reading file "server.public.certificate"
openvpn_config_parser.exe: [DEBUG] x509 cert: cert
openvpn_config_parser.exe: [INFO] Reading file "server.secret.key"
openvpn_config_parser.exe: [ERROR] not a valid client config: does not have a remote

config:
dev tun
persist-key
persist-tun
topology subnet
port 1194
proto udp
keepalive 10 120
ca ca.public.certificate
cert server.public.certificate
key server.secret.key
server 10.89.0.0 255.255.255.0
explicit-exit-notify 1
#user ovpn
#group ovpn
#auth SHA512
tls-version-min 1.2
#tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256
#ncp-ciphers AES-256-GCM:AES-256-CBC
ifconfig-pool-persist ipp.txt
status openvpn-status.log
verb 3
dh dh2048.pem

**Comment by hannesm** [comment]
the `openvpn_config_parser.exe` attempts to validate the configuration as a client configuration and fails. the server part of openvpn is pretty new. I'd suggest to add a `flag` to the configuration parser whether to validate the given configuration as client or server (or maybe just attempt both, and if any succeeds, succeed -- if both fail, show the errors)?

**Comment by whohoho** [comment]
Here is  a pull request with a test for parsing server config: 
https://github.com/roburio/openvpn/pull/38

**Comment by hannesm** [comment]
thanks again, various server configurations are parsed now successfully, esp. since 3e7c8ddbff5f586605006614dadcb4ec1233c0d9 34793c1
