### ISSUE TITLE
verify-x509-name is not parsed

### ISSUE THREAD

**Issue by OtherSystems** [robur-coop/miragevpn#42]
**Client config**
    
    client
    tls-client
    dev tun
    persist-tun
    remote vpn.example 1194 udp
    verify-x509-name vpn.example name
    resolv-retry infinite
    keepalive 10 60
    route-nopull
    route 192.168.2.0 255.255.255.0
    <ca>
    -----BEGIN CERTIFICATE-----
    ca cert
    -----END CERTIFICATE-----
    </ca>
    <cert>
    -----BEGIN CERTIFICATE-----
    cert
    -----END CERTIFICATE-----
    </cert>
    <key>
    -----BEGIN RSA PRIVATE KEY-----
    key
    -----END RSA PRIVATE KEY-----
    </key>
    persist-key
    comp-lzo yes
    verb 3
    cipher AES-256-CBC
    auth SHA256
    lport 0
    verb 4
    auth-nocache
    log /var/log/openvpn.log

**Server config**

    verb 4
    dev uvpn
    dev-type tun
    dev-node /dev/net/tun
    writepid /var/run/openvpn_tunvpn.pid
    script-security 3
    keepalive 10 60
    ping-timer-rem
    persist-tun
    persist-key
    proto udp
    cipher AES-256-CBC
    auth SHA256
    tls-server
    server 192.168.6.128 255.255.255.128
    client-config-dir /etc/openvpn/server
    local vpn.example
    lport 1194
    route-up "/usr/local/sbin/openvpn-set.pl"

**Comment by hannesm** [comment]
thanks for your report, I edited the title to reflect what is the issue here. The provided configuration files are now part of our testsuite (at the moment commented out since parsing fails).
