### ISSUE TITLE
tls-cipher is not parsed

### ISSUE THREAD

**Issue by whohoho** [robur-coop/miragevpn#45]
openvpn_server_config_parser.exe windows-riseup-client.cfg 
openvpn_server_config_parser.exe: [INFO] Reading file "windows-riseup-client.cfg"
openvpn_server_config_parser.exe: [ERROR] : Error at byte offset 988: "tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA\ncipher AES-256-CBC\nauth SHA256\n\ndev tun\n# if dev tun doe"

**Comment by hannesm** [comment]
thanks for your report, I reworded the title -- the respective windows-riseup-client.conf is now part of the repository (in test/sample-configuration-files).
