### ISSUE TITLE
Looking forward to the first release.

### ISSUE THREAD

**Issue by jorgejones7711** [robur-coop/miragevpn#58]
No issue here, just want to drop a note that I'm very much looking forward to the first release. If it's half as good as the mirage-firewall it will be great. A small, purpose built VM for openVPN will be wonderful.

I'd like to point out one of the most significant reasons I still use openvpn rather than wireguard is because of remote-random, so please be sure to include that.

I wish I was a programmer because this is the project I would contribute to.

This will be especially important in the future when somebody gets qubes to work on a librem 5 or a pinephone.

Good luck guys, I'm sure I'm not the only one looking forward to this.

**Comment by hannesm** [comment]
Thanks for your issue. We have this planned, as part of #95. The `Remote_random` is already implemented. We expect a release sometime this year :)
