### ISSUE TITLE
Use `decompress.lzo` instead of the current implementation

### ISSUE THREAD

**Issue by dinosaure** [robur-coop/miragevpn#62]
`decompress.lzo` was specially made for `miragevpn` and support the compression as well. We probably should use it. To be sure about our implementation we can implement a fuzzer on `decompress` and see if everything is good.
- [ ] implement a fuzzer for `decompress.lzo`
- [ ] incorporate `decompress.lzo` into `miragevpn`

**Comment by hannesm** [comment]
thanks, done and merged in #71
