### ISSUE TITLE
Qubes client support

### ISSUE THREAD

**Issue by hannesm** [robur-coop/miragevpn#95]
The plan is to provide a Qubes client, where the configuration may be stored in the QubesDB.

From the issue #3:

qubes: reading config file from QubesDB
- qubesdb keys are capped at 3k bytes, xenstoredb at 4k: https://github.com/QubesOS/qubes-core-qubesdb/blob/master/include/qubesdb.h#L93
- QRexec service that provides the configuration file from dom0 could be a viable, easy way
- read-only block device using qvm-block a -p could work, but since it needs to be a block device that only works for storage backends that are backed by block devices (ie not file), and we have to pad to block size (512) - not nice

**Comment by hannesm** [comment]
I just stumbled upon this comment from @cfcs (in #3): external packages on Qubes can define new VM types (with a template for volume_config - https://github.com/QubesOS/qubes-core-admin/blob/master/qubes/vm/dispvm.py#L55-L83 - by overriding the frontend-devoption we can hardcode the xen block dev id assigned to the volume; this gives us a mapping from petname to block dev id that we can load in the unikernel). This could be a way forward, with tooling to generate unikernel (aka qubes kernel) + vm type (block dev template etc) as an installable rpm. In practice though we can likely make do with the persistent rw and the non-persistent rw (swap) and using QRexec for the configs for most applications. We need to update mirage-kv-xen(or whatever that is called) to allow pointing to specific block ids for these two types of storage. Manifest could point to additional ids (xen id = 202 * 2**8 + minor id, with minor id 0 starting at xvda, xvdb being 1, etc).

I guess we recently talked about using a block device, and the above may be a path for distribution (since we didn't write down how such a configure the MirageVPN unikernel in QubesOS step is supposed to look)...

**Comment by reynir** [comment]
The link was unfortunately pointing to master branch and the file has since then changed. I did some digging, and this might be the state of the file at the time: https://github.com/QubesOS/qubes-core-admin/blob/94c675f7bb77f5e2a67bc11fbcb492c3ffe4fda0/qubes/vm/dispvm.py#L55-L83

**Comment by palainp** [comment]
The current state of mirage allows to target one of the root/private/volatile block devices with `let block = block_of_xenstore_id "51712"` and the id value is done via $202*2^8+minor$ as explained in the comment. If I understand the block configuration in mirage correctly, using `block_of_file` with any string will point to the first block (id=51712).

With the latest release of miage-block-xen (2.1.2), I can read from a tar file imported as the root or volatile volume (via `qvm-volume import mirage-test:root hello.tar`).

With the qubes-mirage-firewall repository and https://github.com/marmarek/qubes-builder-mirage there is an attempt to create an rpm file (the unikernel is embedded in a root disk and booted via multiboot with grub2) this sounds great as it allows booting the VM with the grub2-pvh kernel which is distributed with qubes and doesn't force the installation of a new kernel. However last time I looked into this, it is was buggy in the post-install script (and I haven't dug to much there). If this path is used the preferred block device would be the second one (private).

So to me, in the qubes context, it seems correct to target the private volume (minor=1), and use `qvm-import` to update the configuration (for example in a purpose-created tar file).

**Comment by hannesm** [comment]
See https://github.com/robur-coop/qubes-miragevpn/ and let's track further issues there.
