### ISSUE TITLE
miragevpn-client-lwt privileged port / running as a regular user

### ISSUE THREAD

**Issue by reynir** [robur-coop/miragevpn#96]
The following code generates a random port, but if you're unlucky it may be a privileged port. This may cause the application to fail due to that.
https://github.com/robur-coop/miragevpn/blob/b816eb071622a67b9adb72f8d5a0eeaba228cb14/app/miragevpn_client_lwt.ml#L227

It may not be an issue because I think other parts require privileges (though maybe not as much?). Perhaps we should check for uid = 0.

**Comment by hannesm** [comment]
Let's use only 1024+ ports :) Or not `bind` on the UDP socket (i.e. let the host system stack use an ephemeral port)?

**Comment by reynir** [comment]
#100 fixes this for miragevpn-client-lwt. It may still be an issue for the mirage unikernels if compiled for unix - please reopen if this is an issue.
